### ISSUE TITLE
Strava "one code" security

### ISSUE THREAD

**Issue by skynetbbs** [roboes/strava-club-scraper#4]
@skynetbbs ➜ /workspaces $ python strava-club-scraper/strava-club-scraper.py
Traceback (most recent call last):
  File "/workspaces/strava-club-scraper/strava-club-scraper.py", line 1559, in <module>
    club_members_df = strava_club_members(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/strava-club-scraper/strava-club-scraper.py", line 706, in strava_club_members
    driver = strava_authentication(strava_login=strava_login, strava_password=strava_password)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/strava-club-scraper/strava-club-scraper.py", line 201, in strava_authentication
    next(element for element in driver.find_elements(by=By.XPATH, value='.//*[@data-cy="password"]') if element.is_displayed()).send_keys(strava_password)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

it seems if one connects to web...it asks to enter a code that has been mailed each time...
how to proceed?

**Comment by roboes** [comment]
Hi @skynetbbs, thank you for bringing this issue.

It looks like Strava has changed the login page again  ([a similar issue was recently raised](https://github.com/roboes/strava-club-scraper/issues/2)). I've updated the code accordingly to accommodate these changes.

Please update the code from your side accordingly. Additionally, please note that there is now a new Python package dependency: `pyjanitor`.

I've tested the updated code using Python 3.13.1, and everything is working as expected.

**Comment by test7373** [comment]
Good afternoon. I have the same issue. I'm trying to run your code both on GitHub and on my local machine. Locally, I updated Python to 3.13, but unfortunately, it didn't work.

(venv) root@ha:/home/mi/strava-club-scraper#
python3.13 strava-club-scraper.py
Traceback (most recent call last):
  File "/home/mi/strava-club-scraper/strava-club-scraper.py", line 1568, in <module>
    club_members_df = strava_club_members(
        strava_login=config['STRAVA']['LOGIN'],
    ...<2 lines>...
        timezone=config['GENERAL']['TIMEZONE'],
    )
  File "/home/mi/strava-club-scraper/strava-club-scraper.py", line 715, in strava_club_members
    driver = strava_authentication(strava_login=strava_login, strava_password=strava_password)
  File "/home/mi/strava-club-scraper/strava-club-scraper.py", line 202, in strava_authentication
    field_password = next(element for element in driver.find_elements(by=By.XPATH, value='.//*[@data-cy="password"]') if element.is_displayed())
StopIteration

![Image](https://github.com/user-attachments/assets/13b3a0a7-0e91-4698-97e6-d10922bc1128)

**Comment by roboes** [comment]
Hi @test7373,

Thank you for reaching out.

I've observed that on Strava's desktop website, there's a need for a small delay between entering the email and pressing Enter, as well as the same for the password. This issue doesn't seem to occur on the mobile version (depending on the size of your Selenium WebDriver window, it opens the mobile version).

I've just updated the code. Please give it another try and let me know if it works for you.

**Comment by thomiz** [comment]
Has this stopped working again @roboes? I only get this error when I try to run the authentication on Strava:

```
Traceback (most recent call last):
  File "/home/runner/work/strava-club/strava-club/strava-club-scraper.py", line 1591, in <module>
    club_members_df = strava_club_members(
        strava_user=os.environ['STRAVA_USER'],
    ...<3 lines>...
        timezone=config['GENERAL']['TIMEZONE'],
    )
  File "/home/runner/work/strava-club/strava-club/strava-club-scraper.py", line 736, in strava_club_members
    driver = strava_authentication(strava_user=strava_user, strava_password=strava_password) #aktivitetsaksjonen
  File "/home/runner/work/strava-club/strava-club/strava-club-scraper.py", line [22](https://github.com/hdir/strava-club/actions/runs/13705319048/job/38329096730#step:9:23)3, in strava_authentication
    field_password = next(element for element in driver.find_elements(by=By.XPATH, value='.//*[@data-cy="password"]') if element.is_displayed())
StopIteration
```

To me it looks like the script want to go directly from entering the username to entering the password, but there is a screen in between where you have to click "use password instead" to actually reach the password screen. This should affect the authentication flow somehow?

**Comment by roboes** [comment]
Hi @thomiz,

Thank you for reaching out.

Seems Strava updated the GUI again. The code has been adjusted accordingly and should now work as expected.

**Comment by thomiz** [comment]
Unfortunately, the code still don't fint the correct button @roboes 

> selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//button[text()="Use password instead"]"}

**Comment by roboes** [comment]
I've just updated the code again - both today's and yesterday's updates are working on my end. If it still doesn't work for you, please inspect the "Use password instead" button in your browser (as shown in the screenshot below) to check how it appears:

![Image](https://github.com/user-attachments/assets/9ac36c7a-66e6-4da1-b07a-05e2ba311645)
